### PR TITLE
Get best resolution available to record.

### LINKED ISSUE #17: Limit MediaRecorder size
Some devices can only record up to 1080p. See https://github.com/JakeWharton/Telecine/pull/15.

### PR DESCRIPTION
**Pull request by JakeWharton**
Refs #19. Closes #17.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Confirmed as working!

This needs to apply the aspect ratio of the screen to the camera dimensions so we do not get letter box. Also #22 describes the existing letter box effect we create.

Need to fix both before merging.

**Comment by monxalo** [comment]
Okay, in the case of #22 it can record up to 2160p.
It would be 3840 x 2160 on a 2560 x 1440 screen so we need to add a condition in the case of the camera's resolution surpassing the screen's resolution.

Is the letter box effect present in the resulting videos of this patch?

**Comment by monxalo** [comment]
Created #27 for these fixes.

**Comment by JakeWharton** [comment]
#38

**Pull request closed without merging**
